### ISSUE TITLE
Buy me a coffee link is broken

### ISSUE THREAD

**Issue by illgitthat** [qunash/gpt-3_chrome_extension#3]
Currently, it just links to the image source:
`<img src="https://www.buymeacoffee.com/assets/img/guidelines/download-assets-2.svg" alt="Buy Me A Coffee" style="width: 200px; height: 75px;" >`

Instead, I'll just leave this issue and a thank you to the author for publishing this!

**Comment by qunash** [comment]
Thanks for pointing this out :)
